name: CI

on: 
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first
        if: github.actor == 'aashishmaggam' || github.ref == 'main'
        run: |
          echo "this is ok"
          echo "${{github.ref}}"

      - name: failing
        run: echo "this is not done"
