name: run & deploy
on: 
  push:
    branches:
      - main
  pull_request: 
    types: 
     - opened
     - synchronize
jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event_name.pull_request.base.ref == 'main'
    steps:
      - name: build step
        run: echo "this is building"

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: deployment satge
        run: echo "this app efdeployed"
    



     
      
